# Comprehensive cigar seed data with 50+ premium cigars
from datetime import datetime

# Import the cigar images
from cigar_images_data import MONTECRISTO_IMAGE, PADRON_IMAGE, ARTURO_IMAGE, COHIBA_IMAGE, LIGA_IMAGE

# Using the real images we have, and placeholder for others
PLACEHOLDER_IMAGE = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="

def get_cigar_seed_data():
    return [
        # Premium Cuban Cigars
        {
            "name": "Montecristo No. 2",
            "brand": "Montecristo",
            "image": MONTECRISTO_IMAGE,
            "images": [],
            "strength": "Medium",
            "flavor_notes": ["Cocoa", "Coffee", "Cedar"],
            "origin": "Cuba",
            "wrapper": "Habano",
            "binder": "Cuban",
            "filler": "Cuban",
            "size": "Torpedo (6.1 x 52)",
            "price_range": "25-30",
            "barcode": "7501055300013",
            "average_rating": 9.2,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Cohiba Behike 52",
            "brand": "Cohiba",
            "image": COHIBA_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Honey", "Wood", "Floral"],
            "origin": "Cuba",
            "wrapper": "Habano",
            "binder": "Cuban",
            "filler": "Cuban",
            "size": "Laguito No. 4 (4.3 x 52)",
            "price_range": "40-50",
            "barcode": "7501055300044",
            "average_rating": 9.6,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Cohiba Siglo VI",
            "brand": "Cohiba",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium",
            "flavor_notes": ["Cream", "Coffee", "Vanilla"],
            "origin": "Cuba",
            "wrapper": "Habano",
            "binder": "Cuban",
            "filler": "Cuban",
            "size": "Gran Corona (5.9 x 52)",
            "price_range": "35-45",
            "barcode": "7501055300061",
            "average_rating": 9.3,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Montecristo No. 4",
            "brand": "Montecristo",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium",
            "flavor_notes": ["Cedar", "Nuts", "Leather"],
            "origin": "Cuba",
            "wrapper": "Habano",
            "binder": "Cuban",
            "filler": "Cuban",
            "size": "Petit Corona (5.1 x 42)",
            "price_range": "15-20",
            "barcode": "7501055300078",
            "average_rating": 9.0,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Romeo y Julieta Churchill",
            "brand": "Romeo y Julieta",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium",
            "flavor_notes": ["Tobacco", "Cedar", "Spice"],
            "origin": "Cuba",
            "wrapper": "Habano",
            "binder": "Cuban",
            "filler": "Cuban",
            "size": "Churchill (7 x 47)",
            "price_range": "20-25",
            "barcode": "7501055300085",
            "average_rating": 8.8,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Partagas Serie D No. 4",
            "brand": "Partagas",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Earth", "Leather", "Coffee"],
            "origin": "Cuba",
            "wrapper": "Habano",
            "binder": "Cuban",
            "filler": "Cuban",
            "size": "Robusto (4.9 x 50)",
            "price_range": "18-23",
            "barcode": "7501055300092",
            "average_rating": 9.1,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Hoyo de Monterrey Epicure No. 2",
            "brand": "Hoyo de Monterrey",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium",
            "flavor_notes": ["Cream", "Wood", "Cocoa"],
            "origin": "Cuba",
            "wrapper": "Habano",
            "binder": "Cuban",
            "filler": "Cuban",
            "size": "Robusto (4.9 x 50)",
            "price_range": "20-25",
            "barcode": "7501055300108",
            "average_rating": 8.9,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        
        # Nicaraguan Cigars
        {
            "name": "Padron 1964 Anniversary",
            "brand": "Padron",
            "image": PADRON_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Chocolate", "Coffee", "Nuts"],
            "origin": "Nicaragua",
            "wrapper": "Nicaraguan Maduro",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5 x 50)",
            "price_range": "15-20",
            "barcode": "7501055300020",
            "average_rating": 9.5,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Padron 1926 Serie",
            "brand": "Padron",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Cocoa", "Earth", "Leather"],
            "origin": "Nicaragua",
            "wrapper": "Nicaraguan Maduro",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5.2 x 52)",
            "price_range": "18-23",
            "barcode": "7501055300115",
            "average_rating": 9.4,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Drew Estate Liga Privada No. 9",
            "brand": "Drew Estate",
            "image": LIGA_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Cocoa", "Earth", "Espresso"],
            "origin": "Nicaragua",
            "wrapper": "Connecticut Broadleaf Maduro",
            "binder": "Honduran",
            "filler": "Nicaraguan",
            "size": "Toro (6 x 52)",
            "price_range": "12-15",
            "barcode": "7501055300051",
            "average_rating": 9.1,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Drew Estate Liga Privada T52",
            "brand": "Drew Estate",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Spice", "Pepper", "Leather"],
            "origin": "Nicaragua",
            "wrapper": "Connecticut Habano",
            "binder": "Honduran",
            "filler": "Nicaraguan",
            "size": "Toro (6 x 52)",
            "price_range": "12-15",
            "barcode": "7501055300122",
            "average_rating": 9.0,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Oliva Serie V Melanio",
            "brand": "Oliva",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Coffee", "Cocoa", "Spice"],
            "origin": "Nicaragua",
            "wrapper": "Ecuadorian Sumatra",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5 x 52)",
            "price_range": "10-13",
            "barcode": "7501055300139",
            "average_rating": 9.2,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "My Father Le Bijou 1922",
            "brand": "My Father",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Pepper", "Cedar", "Coffee"],
            "origin": "Nicaragua",
            "wrapper": "Habano Oscuro",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Toro (6 x 52)",
            "price_range": "11-14",
            "barcode": "7501055300146",
            "average_rating": 9.3,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Joya de Nicaragua Antano 1970",
            "brand": "Joya de Nicaragua",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Leather", "Earth", "Spice"],
            "origin": "Nicaragua",
            "wrapper": "Nicaraguan Criollo",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5.5 x 50)",
            "price_range": "8-11",
            "barcode": "7501055300153",
            "average_rating": 8.7,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        
        # Dominican Cigars
        {
            "name": "Arturo Fuente Opus X",
            "brand": "Arturo Fuente",
            "image": ARTURO_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Spice", "Leather", "Pepper"],
            "origin": "Dominican Republic",
            "wrapper": "Dominican Sun Grown",
            "binder": "Dominican",
            "filler": "Dominican",
            "size": "Robusto (5.25 x 50)",
            "price_range": "20-25",
            "barcode": "7501055300037",
            "average_rating": 9.4,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Arturo Fuente Hemingway",
            "brand": "Arturo Fuente",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium",
            "flavor_notes": ["Cedar", "Cream", "Nuts"],
            "origin": "Dominican Republic",
            "wrapper": "Cameroon",
            "binder": "Dominican",
            "filler": "Dominican",
            "size": "Perfecto (7 x 48)",
            "price_range": "10-13",
            "barcode": "7501055300160",
            "average_rating": 8.9,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Davidoff Millennium Blend",
            "brand": "Davidoff",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Coffee", "Cream", "Toast"],
            "origin": "Dominican Republic",
            "wrapper": "Ecuadorian",
            "binder": "Dominican",
            "filler": "Dominican",
            "size": "Robusto (5 x 50)",
            "price_range": "18-22",
            "barcode": "7501055300177",
            "average_rating": 9.0,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Ashton VSG",
            "brand": "Ashton",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Chocolate", "Espresso", "Spice"],
            "origin": "Dominican Republic",
            "wrapper": "Ecuadorian Sun Grown",
            "binder": "Dominican",
            "filler": "Dominican",
            "size": "Robusto (5 x 50)",
            "price_range": "12-16",
            "barcode": "7501055300184",
            "average_rating": 8.8,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "La Flor Dominicana Double Ligero",
            "brand": "La Flor Dominicana",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Pepper", "Earth", "Leather"],
            "origin": "Dominican Republic",
            "wrapper": "Dominican Ligero",
            "binder": "Dominican",
            "filler": "Dominican",
            "size": "Chisel (6.5 x 54)",
            "price_range": "10-14",
            "barcode": "7501055300191",
            "average_rating": 8.9,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        
        # Honduran Cigars
        {
            "name": "Camacho Corojo",
            "brand": "Camacho",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Pepper", "Cedar", "Coffee"],
            "origin": "Honduras",
            "wrapper": "Honduran Corojo",
            "binder": "Honduran",
            "filler": "Honduran",
            "size": "Robusto (5 x 50)",
            "price_range": "8-11",
            "barcode": "7501055300207",
            "average_rating": 8.5,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Alec Bradley Prensado",
            "brand": "Alec Bradley",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Chocolate", "Coffee", "Spice"],
            "origin": "Honduras",
            "wrapper": "Honduran Corojo",
            "binder": "Honduran",
            "filler": "Honduran/Nicaraguan",
            "size": "Robusto (5 x 50)",
            "price_range": "9-12",
            "barcode": "7501055300214",
            "average_rating": 8.8,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Rocky Patel Decade",
            "brand": "Rocky Patel",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Cocoa", "Nuts", "Spice"],
            "origin": "Honduras",
            "wrapper": "Ecuadorian Sumatra",
            "binder": "Honduran",
            "filler": "Honduran/Nicaraguan",
            "size": "Toro (6 x 52)",
            "price_range": "10-13",
            "barcode": "7501055300221",
            "average_rating": 8.7,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        
        # Connecticut Shade (Mild)
        {
            "name": "Macanudo Cafe",
            "brand": "Macanudo",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Mild",
            "flavor_notes": ["Cream", "Nuts", "Toast"],
            "origin": "Dominican Republic",
            "wrapper": "Connecticut Shade",
            "binder": "Mexican",
            "filler": "Dominican",
            "size": "Robusto (5 x 50)",
            "price_range": "6-9",
            "barcode": "7501055300238",
            "average_rating": 7.8,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Ashton Classic",
            "brand": "Ashton",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Mild-Medium",
            "flavor_notes": ["Cedar", "Cream", "Vanilla"],
            "origin": "Dominican Republic",
            "wrapper": "Connecticut Shade",
            "binder": "Dominican",
            "filler": "Dominican",
            "size": "Corona (5.5 x 44)",
            "price_range": "8-11",
            "barcode": "7501055300245",
            "average_rating": 8.2,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Romeo y Julieta 1875",
            "brand": "Romeo y Julieta",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Mild-Medium",
            "flavor_notes": ["Cedar", "Cream", "Hay"],
            "origin": "Dominican Republic",
            "wrapper": "Indonesian",
            "binder": "Dominican",
            "filler": "Dominican",
            "size": "Robusto (5 x 50)",
            "price_range": "5-8",
            "barcode": "7501055300252",
            "average_rating": 7.9,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        
        # Maduro Cigars
        {
            "name": "Perdomo Reserve Champagne",
            "brand": "Perdomo",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium",
            "flavor_notes": ["Cream", "Coffee", "Vanilla"],
            "origin": "Nicaragua",
            "wrapper": "Connecticut",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5 x 54)",
            "price_range": "7-10",
            "barcode": "7501055300269",
            "average_rating": 8.3,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "CAO Brazilia",
            "brand": "CAO",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Chocolate", "Coffee", "Spice"],
            "origin": "Nicaragua",
            "wrapper": "Brazilian Maduro",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Gol (5 x 56)",
            "price_range": "7-10",
            "barcode": "7501055300276",
            "average_rating": 8.4,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Nub Maduro",
            "brand": "Oliva",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Cocoa", "Earth", "Coffee"],
            "origin": "Nicaragua",
            "wrapper": "Brazilian Maduro",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "460 (4 x 60)",
            "price_range": "7-9",
            "barcode": "7501055300283",
            "average_rating": 8.2,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        
        # Boutique/Specialty Cigars
        {
            "name": "Tatuaje Black Label",
            "brand": "Tatuaje",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Pepper", "Leather", "Earth"],
            "origin": "Nicaragua",
            "wrapper": "Ecuadorian Habano",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5 x 50)",
            "price_range": "9-12",
            "barcode": "7501055300290",
            "average_rating": 8.9,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Illusione Rothchildes",
            "brand": "Illusione",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Cedar", "Coffee", "Cream"],
            "origin": "Nicaragua",
            "wrapper": "Nicaraguan Corojo",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Rothschild (4.5 x 50)",
            "price_range": "7-9",
            "barcode": "7501055300306",
            "average_rating": 8.8,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Foundation El Gueguense",
            "brand": "Foundation",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Coffee", "Cocoa", "Spice"],
            "origin": "Nicaragua",
            "wrapper": "Nicaraguan Corojo",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5 x 52)",
            "price_range": "9-12",
            "barcode": "7501055300313",
            "average_rating": 8.7,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        
        # Value/Budget Cigars
        {
            "name": "Punch Gran Puro",
            "brand": "Punch",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Earth", "Cedar", "Spice"],
            "origin": "Honduras",
            "wrapper": "Nicaraguan Habano",
            "binder": "Honduran",
            "filler": "Honduran/Nicaraguan",
            "size": "Robusto (5 x 54)",
            "price_range": "5-7",
            "barcode": "7501055300320",
            "average_rating": 7.9,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "5 Vegas Gold",
            "brand": "5 Vegas",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Mild-Medium",
            "flavor_notes": ["Cream", "Nuts", "Toast"],
            "origin": "Nicaragua",
            "wrapper": "Connecticut Shade",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5 x 55)",
            "price_range": "4-6",
            "barcode": "7501055300337",
            "average_rating": 7.6,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Gran Habano #3 Habano",
            "brand": "Gran Habano",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium",
            "flavor_notes": ["Cedar", "Coffee", "Spice"],
            "origin": "Honduras",
            "wrapper": "Nicaraguan Habano",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5 x 52)",
            "price_range": "4-6",
            "barcode": "7501055300344",
            "average_rating": 7.7,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        
        # Additional Premium Cigars
        {
            "name": "Avo XO Legato",
            "brand": "Avo",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium",
            "flavor_notes": ["Cream", "Vanilla", "Cedar"],
            "origin": "Dominican Republic",
            "wrapper": "Ecuadorian",
            "binder": "Dominican",
            "filler": "Dominican/Peruvian",
            "size": "Robusto (5 x 50)",
            "price_range": "11-14",
            "barcode": "7501055300351",
            "average_rating": 8.5,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Kristoff Maduro",
            "brand": "Kristoff",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Chocolate", "Coffee", "Pepper"],
            "origin": "Nicaragua",
            "wrapper": "Brazilian Maduro",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5.5 x 50)",
            "price_range": "8-11",
            "barcode": "7501055300368",
            "average_rating": 8.6,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "San Cristobal Elegancia",
            "brand": "San Cristobal",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Spice", "Cedar", "Nuts"],
            "origin": "Nicaragua",
            "wrapper": "Ecuadorian Habano",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5 x 52)",
            "price_range": "8-11",
            "barcode": "7501055300375",
            "average_rating": 8.4,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "E.P. Carrillo Pledge",
            "brand": "E.P. Carrillo",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Cedar", "Cream", "Spice"],
            "origin": "Dominican Republic",
            "wrapper": "Connecticut Broadleaf",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5 x 54)",
            "price_range": "10-13",
            "barcode": "7501055300382",
            "average_rating": 8.7,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Warped Futuro",
            "brand": "Warped",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium",
            "flavor_notes": ["Coffee", "Cream", "Nuts"],
            "origin": "Nicaragua",
            "wrapper": "Ecuadorian Habano",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Toro (6 x 50)",
            "price_range": "9-12",
            "barcode": "7501055300399",
            "average_rating": 8.6,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "RoMa Craft Cromagnon",
            "brand": "RoMa Craft",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Pepper", "Earth", "Leather"],
            "origin": "Nicaragua",
            "wrapper": "Connecticut Broadleaf",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5.5 x 52)",
            "price_range": "10-13",
            "barcode": "7501055300405",
            "average_rating": 8.8,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Crowned Heads Four Kicks",
            "brand": "Crowned Heads",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Spice", "Cedar", "Coffee"],
            "origin": "Nicaragua",
            "wrapper": "Ecuadorian Habano",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5.5 x 54)",
            "price_range": "8-11",
            "barcode": "7501055300412",
            "average_rating": 8.5,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Diesel Unlimited",
            "brand": "Diesel",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Full",
            "flavor_notes": ["Pepper", "Leather", "Coffee"],
            "origin": "Nicaragua",
            "wrapper": "Ecuadorian Habano",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5 x 54)",
            "price_range": "7-10",
            "barcode": "7501055300429",
            "average_rating": 8.3,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Aging Room Quattro F55",
            "brand": "Aging Room",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Chocolate", "Coffee", "Cream"],
            "origin": "Nicaragua",
            "wrapper": "Nicaraguan Habano",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Robusto (5.5 x 55)",
            "price_range": "10-13",
            "barcode": "7501055300436",
            "average_rating": 8.9,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Flor de las Antillas",
            "brand": "My Father",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium",
            "flavor_notes": ["Cocoa", "Cedar", "Nuts"],
            "origin": "Nicaragua",
            "wrapper": "Nicaraguan Sun Grown",
            "binder": "Nicaraguan",
            "filler": "Nicaraguan",
            "size": "Toro (6 x 52)",
            "price_range": "8-11",
            "barcode": "7501055300443",
            "average_rating": 9.0,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
        {
            "name": "Liga Undercrown",
            "brand": "Drew Estate",
            "image": PLACEHOLDER_IMAGE,
            "images": [],
            "strength": "Medium-Full",
            "flavor_notes": ["Cocoa", "Leather", "Spice"],
            "origin": "Nicaragua",
            "wrapper": "Brazilian Mata Fina",
            "binder": "Connecticut Habano",
            "filler": "Nicaraguan/Brazilian",
            "size": "Robusto (5 x 54)",
            "price_range": "9-12",
            "barcode": "7501055300450",
            "average_rating": 8.8,
            "rating_count": 0,
            "created_at": datetime.utcnow()
        },
    ]
